### ISSUE TITLE
Don't add url fragment "#" in toc tree of level 1

### ISSUE THREAD

**Issue by nikophil** [doctrine/rst-parser#137]
Hello,

this is related to https://github.com/weaverryan/docs-builder/issues/42

I'm wondering if you'd be ok with this fix? This seems logic not to add the fragment when toc are linking to page and not an anchor inside the page.

It would be an easy fix:
```diff
// ./lib/HTML/Renderers/TocNodeRenderer.php

-    private function generateTarget(?string $url, $title): array
+    private function generateTarget(?string $url, $title, int $level): array
    {
-        $anchor = $this->generateAnchorFromTitle($title);
-
-        $target = $url . '#' . $anchor;
+        $target = $url;
+        if ($level > 1) {
+            $anchor = $this->generateAnchorFromTitle($title);
+            $target .= '#' . $anchor;
+        }
```

thanks.

**Comment by javiereguiluz** [comment]
The main reason we need this change is that it makes URLs ugly and fragile.

For example, if you browse Doctrine docs main page: https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/index.html

When clicking on "Getting Started with Doctrine", you go to:

https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/tutorials/getting-started.html#getting-started-with-doctrine

But I expected you to go to:

https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/tutorials/getting-started.html

This other URL is what you typically expect and it's better because:

* It avoids a browser "jump" on page loading
* It's less fragile, because it won't break when you change the content of the page's `<h1>`

Thanks!

**Comment by greg0ire** [comment]
I agree that a change is need, but I'm not sure this would be the right one. What if a page has several `h1` elements ([apparently that's a thing](https://stackoverflow.com/questions/503925/is-it-alright-to-use-multiple-h1-tags-on-the-same-page-but-style-them-different))? What if that page also has its own toc?

**Comment by javiereguiluz** [comment]
@greg0ire I don't understand your comment 😐 

Let's take again the Doctrine example. The TOC of the index page shows this:

```rst
Getting Started
---------------

* **Tutorial**:
  :doc:`Getting Started with Doctrine <tutorials/getting-started>`

* **Setup**:
  :doc:`Installation & Configuration <reference/configuration>`
```

In my opinion, when you link to `<tutorials/getting-started>` doc, you want to link to the entire page, not to some section inside it. That's why linking to the first (or any other) `<h1>` feels wrong. That's not what I want.

A different thing is when the TOC has nested items. Then, each nested section must point to a section of the page. That's why this PR only proposes to remove the fragment when the TOC level is `1`. I hope it's more clear now.

**Comment by nikophil** [comment]
yes, but @greg0ire is right, the fix I suggested a a little bit naive: it won't work if the page has two `<h1>` because the will both have level = 1.

I'll look a little bit deeper to see what we can do.

**Comment by javiereguiluz** [comment]
OK, there's something I'm missing because I don't understand you 😅 

To me, this would work as follows:

* In a `toctree` directive or when linking with `:doc:`, don't add any fragment because I want to link to the entire page.
* When linking with `:ref:`, add the fragment because I want to link to a specific page section.

**Comment by nikophil** [comment]
toctree is not meant to only link to a page, but it also links into all its titles (anchors).
Look at the first test case here: https://github.com/weaverryan/docs-builder/blob/master/tests/fixtures/source/toctree/index.rst

it results into:
```html
<div class="toctree-wrapper">
    <ul class="toctree toctree-level-1 toctree-length-1">
        <li><a href="file.html#title">Title</a>
            <ul class="toctree toctree-level-2 toctree-length-1">
                <li><a href="file.html#sub-title">Sub title</a></li>
            </ul>
        </li>
    </ul>
</div>
```

because `file.rst` has a "Title" (level 1) and "Sub title"  (level 2).
Imagine this file would look like this:
```rst
Title
======

Sub title
----------

Second main title
=============
```

we would need an anchor for the "Second main title", something like `<li><a href="file.html#second-main-title">Second main title</a>`

So, we can't rely only on toc level...

**Comment by javiereguiluz** [comment]
@nikophil thanks for the explanation. Now I fully understand it 🤓   Yes, you are right that there are some edge-cases to consider for a proper fix. Cheers!

**Comment by greg0ire** [comment]
I don't know if there would be a way to somehow detect that a TOC is the TOC of a section of the site, in which case no anchors are required, or the TOC of single page, in which case they would be useful even for `h1` if there are several of those.

**Comment by nikophil** [comment]
Hi @greg0ire what do you think about that:

- we always add the anchor in url if the page contains its own toc tree
- otherwise, we don't add it only for the first `<h1>` in each page

```php
// ./lib/HTML/Renderers/TocNodeRenderer.php:76

$this->generateTarget(
    $url,
    $title,
    withAnchor: !($level === 1 && $k === 0 && $file !== '/'.$this->environment->getCurrentFileName())
);
```

**Comment by greg0ire** [comment]
I had no idea that we had all that context on the call site, but yes, that does look perfect 👍
