### ISSUE TITLE
Problem in toctree, used with :glob:

### ISSUE THREAD

**Issue by nikophil** [doctrine/rst-parser#18]
Hello,

when using `.. toctree::` with `:glob:`, if some filenames are provided before the `*`, they shouldn't be duplicated, but it should only modify the file order

ex:
![capture du 2018-10-03 12-29-45](https://user-images.githubusercontent.com/10139766/46405578-f17d8100-c708-11e8-9b02-b780a665dc84.png)

when using this toctree:
```rst
.. toctree::
    :glob:

    file
    *
```

we're expecting that it first takes `file.rst`, then `directory/another_file.rst` and that's all
but it takes `file.rst`, and then he takes all the files, including `file.rst`

thank you.

**Comment by weaverryan** [comment]
This is a feature that we only know about because we use it in symfony-docs :). We sometimes will list the most important articles first, then use `*` so that the rest are automatically loaded. Sphinx is smart enough to not repeat any files that were already included.

If this is a pain in the butt to implement, I wouldn't mind changing symfony-docs to not use the `*`.

**Comment by jwage** [comment]
It will be easy to fix.
