### ISSUE TITLE
Function utf8_encode() is deprecated

### ISSUE THREAD

**Issue by ostrolucky** [doctrine/rst-parser#274]
We need to replace this function

```
Deprecated: Function utf8_encode() is deprecated in /Users/gostrolucky/Documents/symfony-docs/_build/vendor/doctrine/rst-parser/lib/Nodes/Table/TableColumn.php on line 30
```

**Comment by smnandre** [comment]
[mb_utf8_encode](https://www.php.net/manual/fr/function.mb-convert-encoding.php) ?

**Comment by smnandre** [comment]
I'm not sure what is expected. Seems to me that since #217 there is a disparity in the internal encodings


## Currently

###  lib/Nodes/[TableNode.php](https://github.com/doctrine/rst-parser/blob/0.5.x/lib/Nodes/TableNode.php)

```php
    public function pushContentLine(string $line): void
    {
        // ...
      $this->rawDataLines[$this->currentLineNumber] = utf8_decode($line);
        // ...
    }
```    

### lib/Nodes/Table/[TableColumn.php](https://github.com/doctrine/rst-parser/blob/0.5.x/lib/Nodes/Table/TableColumn.php)

```php
    public function __construct(string $content, int $colSpan)
    {
        $this->content = utf8_encode(trim($content));
        $this->colSpan = $colSpan;
    }
    
    // ... 
```

And `addContent` was using utf8_encode until recently (https://github.com/doctrine/rst-parser/pull/217) 



## Suggestion

### TableColumn

If this behaviour (encoding from latin-1 to UTF-8) must be kept:

```diff
    public function __construct(string $content, int $colSpan)
    {
-         $this->content = utf8_encode(trim($content));   
+        $this->content = mb_convert_encoding(trim($content), 'UTF-8');
        $this->colSpan = $colSpan;
    }
    
    // ... 
```

### TableNode

Same thing, if and only if you must keep this [converstion](https://www.php.net/manual/fr/function.utf8-decode.php) (i have no idea who calls this method so please correct me)

```diff
    public function pushContentLine(string $line): void
    {
        // ...
-      $this->rawDataLines[$this->currentLineNumber] = utf8_decode($line);
+      $this->rawDataLines[$this->currentLineNumber] = mb_convert_encoding(trim($content), 'UTF-8', 'ISO-8859-1');
        // ...
    }
```    


Tell me if i'm not saying something totally off-topic, i came here for a symfony CI warning so i'm sorry if i don't know the internals/history of this package :)
